{% set name = "vaex-jupyter" %}
{% set version = "0.4.1" %}
{% set sha256 = "338899d17b2ac5134895e17a2691bbca83b343ed3a56b7facad34c2286097184" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=1.0.0,<2
    - vaex-viz
    - bqplot >=0.10.1
    - ipyvolume >=0.4
    - ipyleaflet
    - ipympl
    - ipyvuetify

test:
  imports:
    - vaex.jupyter

about:
  home: https://www.github.com/maartenbreddels/vaex
  doc_url: https://docs.vaex.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter notebook and Jupyter lab support for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
