travis:
  secure:
    BINSTAR_TOKEN: b2d/fnVc0AXIW5nQimE8Z3htxjp7WanheIz3uVDxAt4GKTuuMZZVlF1BKspCaipYZl9+Se6Ye3yQOCNtDCiEMsqHxWCv2Td1Bxnv9R3ppuYptjD7kdhW23nIgsl05vTkJtSl5sAr5Yhy1s0j6H1S/Qt6i65hGZUpvSQuPPwu2Vv1eSYWFT0kyLzIce2yBt/P52ib7inMsxggON4wu5NmO25qxAoP7fix62bj4HWseFAB+hytYAcuYGsS+yTdS65d3DQMfL8+PIhuWipKVfvr9/bb+JajAqSszKZbVkWo/sdnq2XQV7x8Sc1iUlcCHxiEVRa0OjNt0UnFswiNJcBN/+FLe0nYO5QoOElXnZTCMMcdSPLJiX1d0qOtHuUq4uKLGNdpBCTNECFv+/oxGujwK5yCmlRGjAT/T7sJLOmsm8Dkw6rTbGLRy5nwB0EbjuM1JCQlFAKMLc1jVjKq4IWSfIV7p782pJLVsxjF2AJ/CdtAtneGlOFn6QOWkMZ6h80Cf2owqPIEIaEghcY2xGGrqtkSZwGO4l+R1yI91r7r5R4qv2GwQBsV8xD3/p0kzPbxe3Hordn4sDDYHjyXDrXQwq3e6CmeYhXgdhg8U89zQEvBEsIG0t2/wF1TkyHS0IQ5/LZ3O+vXRlAqWLY/DssGSiQquKQmF9TNOGdL//76weA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
