travis:
  secure:
    BINSTAR_TOKEN: JPm0hUleRPWp0Y0/lYOtTcmFdf4ZDBEIAz3KpE8Yx5+Xzh6WrIaHHZ6Z/0355HoPMEHP/q1Pu4OUYTngTujvFPRkXoB3ctilC9oLvZukpN3g4JO8t0yOZaYR7vZTyOgblS4v8b1ZAyRKD0mmIKIYFALzzuiOC9pnRxUgP1+KdWBUqTDrVb1Lkbgfn5MMI8YwWdU/W3SJLJWCv6Ps86WKiJ/yJZfCAy7ykgTsxJ5xUBX66tsaELp3EytkPjWFJysSOxRixvPJv3mjw6akaWxL/YNbRKV1mOijfMT0x5tO3rGr7NQAP56iFXnSGyZwpP3v9b791CPb9B/44jlbucme+OhLLOOBSiJS8x3LxgZt71bLCu++z3onn2lbUjBpk3e9gKWjX5pgoND2rC77L3j9WVryc1jGoemN7iQFO488IKmq3jQC18YodTF45fwM9znHU9fZDZm484GqB9wIiU+qFATW7zrMJ9APGWUbBTvTilPZTD/92IJtBv7spOX561nFkTAijSDXadHNdkXPqJ+x5Wm3pAY6WdgMjDFZ8UFjpVa2v1Hcz6fsRAxfuye33Mj/RZIbZMCJkOIX75gEHg2rLXuhRZ46mX3x6QGN6z+tIwFWL0gtQKYP93qpT+VXP3UB6MSTELmCD7wf7YNU3raPNh6dBbPru8jVyMxNOnPkkLA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
