travis:
  secure:
    BINSTAR_TOKEN: feUSvRH6+iUQSxHJcpYExiiky15jE58LdpHxCCiZvv3kRq//lJgStR7tRALlzkaeHjLMbM9TPVdQTCzkSljkYyMmSlubBgQb1+iyEJTvKhH7bDq3Ab6nFKpYbPicFf60ibKphI3XMfRnMGZITKEXlXR3+qmsarN8ydQz+Ybd1H43a715W+Jh9ZkAoX2/x/WSH1w/K2vFh8l9WomwBqtWvlSAWam6UUQQvrHjqLB/sQdmXUqWWn+L/vtPf2kYbRwBJ+WhRA4syjEO8zSm8YtePD9LNTd2h6c9i66SFgnnDh888E2y77OrJmXCD9GUGSyGX1B6d6ScYsot0ykwlqskf8lNjmvldolAP1iItbFHCSUOTOvROA8q8TDvrNG25m07aRypPaFHC12VywT7RjgpHpmUmeIJkz+f+3oRfAFcS6Ai45wH1kbBYQdn8zj4vfsRN7DQz08w8h5eryWgl//Z5Zkqr4nmogmsY/7fn5cvp8VqYw8+4F0rVGvivraXtPyvUph/qP1uaqvDgKqCQq+R6ivVBbmZ/sqWoJvZj8KPzv/YUYYHFNYbAvhnR50KyfBCIhHihUm8kHr8BihmGmRE0grBCIDFNE9QAkhw+wTwe0R6hlJsDKLARqYjZYDSMXv7euCrhcdWT3rVIu8gBhdVQNFDsqHpio4gfmzixu1cIhI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
